const TITLE_CHANGE = 'TITLE_CHANGE';
const CONTENT_CHANGE = 'CONTENT_CHANGE';
const CLEAR_INPUT = 'CLEAR_INPUT';
const ADD_NOTE = 'ADD_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';
const SELECT_ACTIVE_NOTES = 'SELECT_ACTIVE_NOTEs';
const SELECT_DELETED_NOTES = 'SELECT_DELETED_NOTES';

export {
  TITLE_CHANGE,
  CONTENT_CHANGE,
  CLEAR_INPUT,
  ADD_NOTE,
  DELETE_NOTE,
  SELECT_ACTIVE_NOTES,
  SELECT_DELETED_NOTES
}